### ISSUE TITLE
pip package broken - requirements.txt not found

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/rmageddon-cli#5]
```
(base) [lukas@qbic-hiwi1 r-lint-cli]$ pip3 install r-lint
Collecting r_lint
  Downloading https://files.pythonhosted.org/packages/32/ca/b4aec666b4e04e98325c20733bf29c4779ed2662605d2a5370cbf21c0b93/r-lint-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7idcwjwd/r-lint/setup.py", line 14, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7idcwjwd/r-lint/

```

**Comment by Zethson** [comment]
https://github.com/qbicsoftware/rmageddon-cli/commit/d2f9ea53bd856c3ac0c0dd377efc55bb822dc77c
